# This is a basic workflow to help you get started with Actions

name: Twitter post 16 PM UTC

# Controls when the workflow will run
on:

# Run every day at 05:02 UTC
  schedule:
  - cron:  '02 16 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        env:
          CLIENT_ID_FROST: ${{secrets.CLIENT_ID_FROST}}
          TWITTER_API_KEY: ${{secrets.TWITTER_API_KEY}}
          TWITTER_API_KEY_SECRET: ${{secrets.TWITTER_API_KEY_SECRET}}
          TWITTER_ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
          TWITTER_ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
          ENDPOINT_RUTE: ${{secrets.ENDPOINT_RUTE}}
          NUM_ITERATIONS: 7
        run: python daily_twitter.py
