# This is a basic workflow to help you get started with Actions

name: Værvarsel

# Controls when the workflow will run
on:

# Run every hour at the 3rd minute
  schedule:
  - cron:  '03 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        env:
          CLIENT_ID_FROST: ${{secrets.CLIENT_ID_FROST}}
          AUTH_TOKEN_COURIER: ${{secrets.AUTH_TOKEN_COURIER}}
          ENDPOINT_RUTE: ${{secrets.ENDPOINT_RUTE}}
        run: |
          timedatectl
          python notification.py
