name: Summary 24
on:
  #Run every day at 05:05 UTC (06:05 CET)
  schedule:
  - cron:  '05 05 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        env:
          CLIENT_ID_FROST: ${{secrets.CLIENT_ID_FROST}}
          AUTH_TOKEN_COURIER: ${{secrets.AUTH_TOKEN_COURIER}}
        run: |
          timedatectl
          python daily_email.py
