# This is a basic workflow to help you get started with Actions

name: Twitter post

# Controls when the workflow will run
on:

# Run every day at the 17:02 UTC
  schedule:
  - cron:  '02 17 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run script
        env:
          CLIENT_ID_RUTE: ${{secrets.CLIENT_ID_RUTE}}
          CLIENT_SECRET_RUTE: ${{secrets.CLIENT_SECRET_RUTE}}
          CLIENT_ID_FROST: ${{secrets.CLIENT_ID_FROST}}
          CLIENT_SECRET_FROST: ${{secrets.CLIENT_SECRET_FROST}}
          AUTH_TOKEN_COURIER: ${{secrets.AUTH_TOKEN_COURIER}}
          AUTH_TOKEN_COURIER_24: ${{secrets.AUTH_TOKEN_COURIER_24}}
          TWITTER_NOTIFICATION: True
          TWITTER_API_KEY: ${{secrets.TWITTER_API_KEY}}
          TWITTER_API_KEY_SECRET: ${{secrets.TWITTER_API_KEY_SECRET}}
          TWITTER_BEARER_TOKEN: ${{secrets.TWITTER_BEARER_TOKEN}}
          TWITTER_ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
          TWITTER_ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}
          ENPOINT_RUTE: ${{secrets.ENDPOINT_RUTE}}
        run: python main.py
